spring:
  application:
    name: movie-catalog-service
  cloud:
    config:
      uri: http://localhost:8888/
server:
  port: 8081

management.endpoints.web.exposure.include: health,info,prometheus

resilience4j:
  circuitbreaker:
    instances:
      generic:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s

